version: '3.8'

services:
  pingpong1:
    build: .
    environment:
      - PORT=5000
      - PONG=Hello from Instance 1
    ports:
      - "5000:5000"

  pingpong2:
    build: .
    environment:
      - PORT=5001
      - PONG=Greetings from Instance 2
    ports:
      - "5001:5001"
